.TH crypt3 1
.SH NAME
crypt3 \- password encryption
.SH SYNOPSIS
\fBcrypt3\fR [\fIOPTIONS]\fR [\fIPASSWORD\fR...]
.SH DESCRIPTION
\fBcrypt3\fR encrypts a password using \fBcrypt\fR(3).
.SS "Terminal Usage"
If run from a terminal without any passwords on the command line,
\fBcrypt3\fR reads one password fron the terminal without echo and confirms it.
It then prints the encrypted form of the password.
.SS "File Usage"
If run without any passwords on the command line with a non-terminal on standard input,
\fBcrypt3\fR reads passwords from standard input and prints the encrypted form of each.
It stops when the input reaches end of file.
.SS "Command-Line Usage"
If run with passwords on the command line,
\fBcrypt3\fR prints the encrypted form of each password.
.PP
This isn't very secure since command line are visible in \fBps\fR(1) output,
but it's convenient for low-value passwords.
.SH OPTIONS
.TP
.B \-\-des
Traditional iterated DES encryption.
Comedically insecure.
.TP
.B \-\-md5
Iterated MD5.
.TP
.B \-\-sha256
Iterated SHA256.
.TP
.B \-\-sha512
Iterated SHA512.
This is the default.
.TP
.B \-\-help
Display help message.
.TP
.B \-\-version
Display version string.
.SH "SEE ALSO"
.BR crypt (3)
